import { Category } from '../../../types/category';
import { Product } from '../../../types/product';

export const products: Product[] = [
  {
    id: '13',
    title: 'Antibacterial Spray',
    description: 'Top seller in Canadian organic markets',
    price: 7.48,
    imageSrc: 'https://m.media-amazon.com/images/I/71EGJITRX0L._AC_SL1500_.jpg',
    categories: ['pharmacy', 'cleaning', 'spray', 'disinfectant'],
    isMadeInCanada: false,
    amazonUrl: 'https://www.amazon.ca/Febreze-Antibacterial-Fabric-Refresher-700/dp/B0CWSCCXXB/ref=sr_1_5?crid=JR6HQXMBDWWJ&dib=eyJ2IjoiMSJ9.GgJ23V9WZ2s92yEpG7mi-s7G1uzTiG0J3qUSh2LG5ByKuD-tmkaJbrTI0NHKfFtXts9vQwm04Qtv8bu8o19-ec6dCHq-1JBKC6nifAd75FYlwTx2OqdRF0_YX3nVO7vsdOoE-kiEIhh-TBZ0BeZLKighkBbm_71YP2RUNd5JENU8aPhao6KXbSns6qfL-kPiXdw1IvA_4KJZjRo0JcoJckKGh2te5HAhkDodTNVRPOheXlM61ycSphVFrfy-916t240ELT9I8EEW6yDcB9DtJ3xoI1gMjNzGuu1PMxVTbjSydBL5gUghO8E6-Wf2wsmh6msRUz3aWiK6kHIiVPtJIxB3smnX4JGq8CpTlcSogBNceWang2yOjwTG8NwUvsjQcU5-cvXjhBK-wELdiYpRI6E9Pe8gAxpL87td6BPH9dqDXkjpqxMWX7P2WBkzFuDF.VQAle_bXYNf6HLhNYI5XfiFHiq6MiWy5jqbsCt97f2Q&dib_tag=se&keywords=Antibacterial%2BSpray&qid=1743223536&sprefix=antibacterial%2Bspray%2Caps%2C81&sr=8-5&th=1',
    walmartUrl: 'https://www.walmart.ca/en/ip/Febreze-Antibacterial-Fabric-Refresher/6000207494519?classType=REGULAR&athbdg=L1102&from=/search',
  },
  {
    id: '14',
    title: 'Eucalyptus Oil',
    description: 'Popular among Canadian athletes',
    price: 10.98,
    imageSrc: 'https://m.media-amazon.com/images/I/71q-nSz6KKL._AC_SL1500_.jpg',
    categories: ['health', 'oil', 'natural', 'therapeutic'],
    isMadeInCanada: false,
    amazonUrl: 'https://www.amazon.ca/Thursday-Plantation-100-Pure-Eucalyptus/dp/B0196LGBFG/ref=sr_1_12?crid=334OSZX3X41KP&dib=eyJ2IjoiMSJ9.eEldjIm3oa8J5QZ-RaLdNoPbnA3xHs8WsM2pRa7Mufxhmp38n2LMefKk8tXdP_VFtQCWe7girHIWaY23hBDMSoh5eALQuR-dAj3N8ruTDDsIzPFbP-o8xkdjRxMgVWtWD238bp-NlS8UgMuB6I9V6SX1waruxWiWpv_W963R86To4ZXjku0F5gu4BSSpetXcbblirmFWzg0bp15FaW4gi4sWfmu-P5SxvZp412sh6LkeqrDE5JFq1esY5vEK8cQnT5iyAEgVMZdt3o2yRH0E_1ebeWpOBaN0kWcf1XjEUZ9koTD3CM5JoEin__OninZVbWqoBddhDLM0O9-luPknZnnkfAmvIuJjwSsuAHShaNooTc2lg_ly-shS0UixH5qcmNySk6OORiAo2jrfJckW0s9OultUu_6f_cin-hdsz5Bc0qya_E8EcVcq8VW3DqfV.dLOSdA-76F74L0wnp_eV5FjdVvz6LHXOIjwhfSVzBjk&dib_tag=se&keywords=Eucalyptus+Oil&qid=1743224441&sprefix=eucalyptus+oil%2Caps%2C150&sr=8-12',
    walmartUrl: 'https://www.walmart.ca/en/ip/thursday-plantation-100-pure-eucalyptus-oil-adult/6000195953525?classType=REGULAR&athbdg=L1102&from=/search',
  },
  {
    id: '15',
    title: 'Eucalyptus Oil',
    description: 'Infused with maple and lavender pack of 6',
    price: 19.54,
    imageSrc: 'https://m.media-amazon.com/images/I/81WdPxYkHuL._AC_SL1440_.jpg',
    categories: ['beauty', 'oil', 'aromatherapy', 'natural', 'fragrance'],
    isMadeInCanada: false,
    amazonUrl: 'https://www.amazon.ca/PURE-AROMA-Essential-Oils-Aromatherapy/dp/B01KWIKUU4/ref=sr_1_8?crid=1JNQGJFK9L482&dib=eyJ2IjoiMSJ9.eEldjIm3oa8J5QZ-RaLdNnvklkMcesBjaOPRTuQiSCTXGhYSNwQgEwtkwC6x9lPSRvR0Jlm-fejgCvhZa7acCRjxypBBpd6ZoHfEcNDqxpP_kD_8r0KNRnbQMCYXO2DwenZJ1_nwZUlE-m4bfu2IUATsxFboFe0mJV9e5xk-Lrx6XdtNbH_i4jkEC4s7NlZ9_TuLgom-PhdLh4o94WubbHCaQRhpblBDQtwGjc-aTwLlINirHqQU35Fa_DDxAlTUT5qYfwDirShPLMBtYiu1qs1xYFmf8k9nCcCCMKS5Omuxy_yeigNpMF9Vpqv6I3LVHCHXiIjzTva19SMX-Faubv0mdv1BybaaesNb156bBUL23FnauYFl0KlRPuvZsncEPefHePyQQOy_1wAhVCgX6-83ot-EjogOWXSSK06t4YxvsHgxPj2_ptnZE3p9Sjxn.NGdIk63V5qyfB9vmxM9Q6pABI_QqTs9vugERd59-LmQ&dib_tag=se&keywords=eucalyptus+oil+diffuser&qid=1743224733&sprefix=eucalyptus+oil+diffuser%2Caps%2C130&sr=8-8',
    walmartUrl: 'https://www.walmart.ca/en/ip/10ML-Pure-Natural-Plant-Essential-Oils-Aroma-Essential-Oil-Diffuser-Eucalyptus-Vanilla-Mint-Lavender-Rose-Tea-Tree-Essential-Oil/3FDSWY927HXL?classType=VARIANT&from=/search',
  },
  {
    id: '16',
    title: 'Hair Serum',
    description: 'Infused with maple and lavender',
    price: 8.67,
    imageSrc: 'https://m.media-amazon.com/images/I/71bESsRoZGL._AC_SL1500_.jpg',
    categories: ['beauty', 'haircare', 'serum', 'personal care'],
    isMadeInCanada: false,
    amazonUrl: 'https://www.amazon.ca/LOreal-Paris-Expertise-Hyaluron-Hyaluronic/dp/B09NB2FZ51/ref=sr_1_6?crid=1VDDHVMOKE4AB&dib=eyJ2IjoiMSJ9.LgbYBrhZHCfrnu9A5jzZ_qp_GSRUycDFe2VTJiF4t_7Dc5bNcFCWC6d17urj4gJvB7UGnRUPS_yhoXtfwXE71ct0UjXkhCdgoAcxr7gHgJPXfnfi6r-8Q6YusEvVYkbnosgEZ44JjP2nlQ0pRWzCUIras6xOMp1cuW4Sal3XJqpysOrx32FcLzBGQ7-WfY9pptHGCXUfsc3pg8ZwlES1kS9GVdrPH-eGtpxXGmnK6kgm7qsNCvhHLFWGw439I9XiszfcpHrL-T_H8jdMgfR4X0-6n0_cV3cmzk4YJq69BGKQyC9_pxO4Sdp1q0V8mUxftU95psbUqPmTcK56pv3v7lRS5amp32YLiQQwS9TO_kPHzgyhE6H8aQOFzY7D-l1YIG72I591bCERapjQviC8KwPF8iEZDMlJVhUBcAVFQeH0_QsaYD3bA1tuA9xgCgd-.k3mof4ewo728Nnu7BWspqmfhKskA15SkcoeIwIp1EyI&dib_tag=se&keywords=Hair+Serum&qid=1743225089&sprefix=hair+serum%2Caps%2C176&sr=8-6',
    walmartUrl: 'https://www.walmart.ca/en/ip/loreal-paris-hair-expertise-hair-serum-with-hyaluronic-acid/6000204437196?classType=REGULAR&athbdg=L1102&from=/search',
  },
  {
    id: '17',
    title: 'Spirulina Powder',
    description: 'Perfect for cold Canadian winters',
    price: 45.18,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=17',
    categories: ['grocery', 'supplement', 'superfood', 'health'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '18',
    title: 'Vitamin C Tablets',
    description: 'Vegan, cruelty-free and eco-friendly',
    price: 68.45,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=18',
    categories: ['health', 'supplement', 'vitamins', 'immune support', 'vegan'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '19',
    title: 'Kombucha Starter Kit',
    description: 'Made with natural Canadian ingredients',
    price: 60.86,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=19',
    categories: ['grocery', 'fermentation', 'beverage', 'natural', 'starter kit'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '20',
    title: 'Ice Skates',
    description: 'Crafted in small batches in Ontario',
    price: 39.41,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=20',
    categories: ['sports', 'winter', 'skating', 'outdoors', 'canadian made'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '22',
    title: 'Beard Oil',
    description: 'Perfect for cold Canadian winters',
    price: 17.24,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=22',
    categories: ['natural', 'oil'],
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '23',
    title: 'Sleep Gummies',
    description: 'Infused with maple and lavender',
    price: 87.91,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=23',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '24',
    title: 'Antibacterial Spray',
    description: 'Sourced sustainably from BC forests',
    price: 31.95,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=24',
    categories: ['cleaning', 'disinfectant', 'pharmacy', 'spray'],
    isMadeInCanada: true,
    amazonUrl: '',
    walmartUrl: '',
  },
  {
    id: '25',
    title: 'Rose Water Spray',
    description: 'Crafted in small batches in Ontario',
    price: 12.33,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=25',
    categories: ['cleaning', 'disinfectant', 'pharmacy', 'spray'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '26',
    title: 'Arnica Gel',
    description: 'Perfect for cold Canadian winters',
    price: 28.03,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=26',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '27',
    title: 'Arnica Gel',
    description: 'Popular among Canadian athletes',
    price: 99.22,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=27',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '28',
    title: 'Kombucha Starter Kit',
    description: 'Crafted in small batches in Ontario',
    price: 32.63,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=28',
    categories: ['fermentation', 'grocery', 'natural', 'starter kit'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '29',
    title: 'Natural Deodorant',
    description: 'Vegan, cruelty-free and eco-friendly',
    price: 87.91,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=29',
    categories: ['vegan'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '30',
    title: 'Muscle Rub',
    description: 'Sourced sustainably from BC forests',
    price: 43.96,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=30',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: '',
    walmartUrl: '',
  },
  {
    id: '31',
    title: 'Ginger Chews',
    description: 'Harvested fresh from Nova Scotia',
    price: 21.73,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=31',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '32',
    title: 'Elderberry Syrup',
    description: 'Family-owned brand from Alberta',
    price: 29.32,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=32',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '33',
    title: 'Recycled Notebook',
    description: 'Infused with maple and lavender',
    price: 80.2,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=33',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '34',
    title: 'Peppermint Lip Balm',
    description: 'Crafted in small batches in Ontario',
    price: 95.12,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=34',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '35',
    title: 'Thermal Socks',
    description: 'Crafted in small batches in Ontario',
    price: 5.74,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=35',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '36',
    title: 'Apple Chips',
    description: 'Vegan, cruelty-free and eco-friendly',
    price: 56.91,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=36',
    categories: ['vegan'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '37',
    title: 'Hemp Protein Powder',
    description: 'Popular among Canadian athletes',
    price: 51.55,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=37',
    categories: ['grocery', 'health', 'superfood', 'supplement'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '38',
    title: 'Ice Skates',
    description: 'Made with natural Canadian ingredients',
    price: 21.64,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=38',
    categories: ['skating', 'sports', 'winter'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '39',
    title: 'Granola Mix',
    description: 'Perfect for cold Canadian winters',
    price: 76.84,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=39',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '40',
    title: 'Kombucha Starter Kit',
    description: 'Harvested fresh from Nova Scotia',
    price: 18.91,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=40',
    categories: ['fermentation', 'grocery', 'natural', 'starter kit'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '41',
    title: 'Granola Mix',
    description: 'Top seller in Canadian organic markets',
    price: 32.43,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=41',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '42',
    title: 'Black Currant Lozenges',
    description: 'Vegan, cruelty-free and eco-friendly',
    price: 85.1,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=42',
    categories: ['vegan'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '43',
    title: 'Body Wash',
    description: 'Sourced sustainably from BC forests',
    price: 84.45,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=43',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '44',
    title: 'Magnesium Oil',
    description: 'Harvested fresh from Nova Scotia',
    price: 66.68,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=44',
    categories: ['natural', 'oil'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '45',
    title: 'Apple Chips',
    description: 'Top seller in Canadian organic markets',
    price: 67.48,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=45',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '46',
    title: 'Charcoal Toothpaste',
    description: 'Infused with maple and lavender',
    price: 83.96,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=46',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '47',
    title: 'Antibacterial Spray',
    description: 'Made with natural Canadian ingredients',
    price: 57.41,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=47',
    categories: ['cleaning', 'disinfectant', 'pharmacy', 'spray'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '48',
    title: 'Energy Bar',
    description: 'Made with natural Canadian ingredients',
    price: 9.71,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=48',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: '',
  },
  {
    id: '49',
    title: 'Bamboo Toothbrush',
    description: 'Sourced sustainably from BC forests',
    price: 63.4,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=49',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '50',
    title: 'Hand Cream',
    description: 'Top seller in Canadian organic markets',
    price: 75.9,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=50',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '51',
    title: 'Recycled Notebook',
    description: 'Crafted in small batches in Ontario',
    price: 88.26,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=51',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '52',
    title: 'Hand Cream',
    description: 'Harvested fresh from Nova Scotia',
    price: 78.45,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=52',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: '',
    walmartUrl: '',
  },
  {
    id: '53',
    title: 'Gluten-Free Flour',
    description: 'Infused with maple and lavender',
    price: 21.07,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=53',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '54',
    title: 'Vitamin C Tablets',
    description: 'Infused with maple and lavender',
    price: 92.89,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=54',
    categories: ['health', 'supplement', 'vitamins'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '55',
    title: 'Body Wash',
    description: 'Top seller in Canadian organic markets',
    price: 16.2,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=55',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: '',
  },
  {
    id: '56',
    title: 'Hand Cream',
    description: 'Sourced sustainably from BC forests',
    price: 26.94,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=56',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '57',
    title: 'Zinc Supplements',
    description: 'Family-owned brand from Alberta',
    price: 76.02,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=57',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: '',
  },
  {
    id: '58',
    title: 'Ice Skates',
    description: 'Sourced sustainably from BC forests',
    price: 84.97,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=58',
    categories: ['skating', 'sports', 'winter'],
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '59',
    title: 'Natural Mascara',
    description: 'Family-owned brand from Alberta',
    price: 85.16,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=59',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '60',
    title: 'Beard Oil',
    description: 'Harvested fresh from Nova Scotia',
    price: 78.94,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=60',
    categories: ['natural', 'oil'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '61',
    title: 'Gluten-Free Flour',
    description: 'Made with natural Canadian ingredients',
    price: 37.19,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=61',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '62',
    title: 'Bamboo Toothbrush',
    description: 'Sourced sustainably from BC forests',
    price: 72.42,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=62',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '63',
    title: 'Probiotic Capsules',
    description: 'Vegan, cruelty-free and eco-friendly',
    price: 38.84,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=63',
    categories: ['vegan'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '64',
    title: 'Zinc Supplements',
    description: 'Infused with maple and lavender',
    price: 8.23,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=64',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '65',
    title: 'Rose Water Spray',
    description: 'Popular among Canadian athletes',
    price: 81.71,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=65',
    categories: ['cleaning', 'disinfectant', 'pharmacy', 'spray'],
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '66',
    title: 'Hand Cream',
    description: 'Family-owned brand from Alberta',
    price: 26.22,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=66',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '67',
    title: 'Ginger Chews',
    description: 'Family-owned brand from Alberta',
    price: 74.15,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=67',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '68',
    title: 'Body Wash',
    description: 'Made with natural Canadian ingredients',
    price: 6.83,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=68',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '69',
    title: 'Trail Mix',
    description: 'Harvested fresh from Nova Scotia',
    price: 66.01,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=69',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '70',
    title: 'Vitamin C Tablets',
    description: 'Harvested fresh from Nova Scotia',
    price: 85.95,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=70',
    categories: ['health', 'supplement', 'vitamins'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '71',
    title: 'Body Wash',
    description: 'Perfect for cold Canadian winters',
    price: 45.74,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=71',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '72',
    title: 'Hand Cream',
    description: 'Family-owned brand from Alberta',
    price: 26.73,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=72',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '73',
    title: 'Peppermint Lip Balm',
    description: 'Family-owned brand from Alberta',
    price: 50.09,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=73',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: '',
  },
  {
    id: '74',
    title: 'Zinc Supplements',
    description: 'Made with natural Canadian ingredients',
    price: 88.97,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=74',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '75',
    title: 'Energy Bar',
    description: 'Crafted in small batches in Ontario',
    price: 53.54,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=75',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '76',
    title: 'Rose Water Spray',
    description: 'Made with natural Canadian ingredients',
    price: 84.78,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=76',
    categories: ['cleaning', 'disinfectant', 'pharmacy', 'spray'],
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '77',
    title: 'Ginger Chews',
    description: 'Harvested fresh from Nova Scotia',
    price: 68.32,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=77',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '78',
    title: 'Ice Skates',
    description: 'Made with natural Canadian ingredients',
    price: 34.02,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=78',
    categories: ['skating', 'sports', 'winter'],
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: '',
  },
  {
    id: '79',
    title: 'Face Toner',
    description: 'Crafted in small batches in Ontario',
    price: 29.74,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=79',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '80',
    title: 'Peppermint Lip Balm',
    description: 'Top seller in Canadian organic markets',
    price: 67.56,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=80',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '81',
    title: 'Beard Oil',
    description: 'Popular among Canadian athletes',
    price: 18.34,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=81',
    categories: ['natural', 'oil'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '82',
    title: 'Sleep Gummies',
    description: 'Sourced sustainably from BC forests',
    price: 33.15,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=82',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '83',
    title: 'Arnica Gel',
    description: 'Popular among Canadian athletes',
    price: 5.86,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=83',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '84',
    title: 'Salmon Jerky',
    description: 'Family-owned brand from Alberta',
    price: 36.26,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=84',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '85',
    title: 'Eucalyptus Oil',
    description: 'Infused with maple and lavender',
    price: 55.13,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=85',
    categories: ['natural', 'oil'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '86',
    title: 'Salmon Jerky',
    description: 'Perfect for cold Canadian winters',
    price: 29.11,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=86',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '87',
    title: 'Aloe Vera Gel',
    description: 'Crafted in small batches in Ontario',
    price: 72.73,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=87',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '88',
    title: 'Energy Bar',
    description: 'Perfect for cold Canadian winters',
    price: 18.38,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=88',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '89',
    title: 'Spirulina Powder',
    description: 'Popular among Canadian athletes',
    price: 95.07,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=89',
    categories: ['grocery', 'health', 'superfood', 'supplement'],
    isMadeInCanada: true,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '90',
    title: 'Peppermint Lip Balm',
    description: 'Perfect for cold Canadian winters',
    price: 93.33,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=90',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '91',
    title: 'Arnica Gel',
    description: 'Perfect for cold Canadian winters',
    price: 28.45,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=91',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '92',
    title: 'Gluten-Free Flour',
    description: 'Harvested fresh from Nova Scotia',
    price: 51.77,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=92',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '93',
    title: 'Ginger Chews',
    description: 'Infused with maple and lavender',
    price: 19.89,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=93',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '94',
    title: 'Maple Soap',
    description: 'Harvested fresh from Nova Scotia',
    price: 71.95,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=94',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: '',
    walmartUrl: '',
  },
  {
    id: '95',
    title: 'Organic Shampoo',
    description: 'Infused with maple and lavender',
    price: 69.76,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=95',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '96',
    title: 'Magnesium Oil',
    description: 'Infused with maple and lavender',
    price: 7.65,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=96',
    categories: ['natural', 'oil'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '97',
    title: 'Pumpkin Seed Butter',
    description: 'Infused with maple and lavender',
    price: 98.65,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=97',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '98',
    title: 'Energy Bar',
    description: 'Harvested fresh from Nova Scotia',
    price: 30.79,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=98',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '99',
    title: 'Trail Mix',
    description: 'Perfect for cold Canadian winters',
    price: 53.18,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=99',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '100',
    title: 'Natural Mascara',
    description: 'Family-owned brand from Alberta',
    price: 16.05,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=100',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '101',
    title: 'Eye Cream',
    description: 'Sourced sustainably from BC forests',
    price: 53.25,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=101',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '102',
    title: 'Natural Deodorant',
    description: 'Harvested fresh from Nova Scotia',
    price: 72.88,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=102',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '103',
    title: 'Spirulina Powder',
    description: 'Family-owned brand from Alberta',
    price: 96.9,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=103',
    categories: ['grocery', 'health', 'superfood', 'supplement'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '104',
    title: 'Arnica Gel',
    description: 'Perfect for cold Canadian winters',
    price: 95.55,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=104',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '105',
    title: 'Lemon Balm Tea',
    description: 'Sourced sustainably from BC forests',
    price: 96.43,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=105',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '106',
    title: 'Chia Seeds',
    description: 'Sourced sustainably from BC forests',
    price: 41.66,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=106',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '107',
    title: 'Zinc Supplements',
    description: 'Harvested fresh from Nova Scotia',
    price: 30.74,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=107',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '108',
    title: 'Trail Mix',
    description: 'Popular among Canadian athletes',
    price: 49.89,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=108',
    categories: ['general'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '109',
    title: 'Reusable Cotton Pads',
    description: 'Family-owned brand from Alberta',
    price: 91.27,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=109',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '110',
    title: 'Organic Tea',
    description: 'Vegan, cruelty-free and eco-friendly',
    price: 75.16,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=110',
    categories: ['vegan'],
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '111',
    title: 'Sleep Gummies',
    description: 'Sourced sustainably from BC forests',
    price: 87.96,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=111',
    categories: ['general'],
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '112',
    title: 'Hair Conditioner',
    description: 'Top seller in Canadian organic markets',
    price: 16.49,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=112',
    categories: ['grocery'],
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
];

export const categories: Category[] = [
  { id: 'all', name: 'All Products' },
  { id: 'grocery', name: 'Grocery' },
  { id: 'health', name: 'Health' },
  { id: 'beauty', name: 'Beauty' },
  { id: 'pharmacy', name: 'Pharmacy' },
];
