import { Category } from '../../../types/category';
import { Product } from '../../../types/product';

export const products: Product[] = [
  {
    id: '13',
    title: 'Antibacterial Spray',
    description: 'Top seller in Canadian organic markets',
    price: 62.43,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=13',
    category: 'pharmacy',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '14',
    title: 'Eucalyptus Oil',
    description: 'Popular among Canadian athletes',
    price: 36.62,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=14',
    category: 'health',
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '15',
    title: 'Eucalyptus Oil',
    description: 'Infused with maple and lavender',
    price: 65.12,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=15',
    category: 'beauty',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '16',
    title: 'Hair Serum',
    description: 'Infused with maple and lavender',
    price: 78.8,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=16',
    category: 'health',
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: '',
  },
  {
    id: '17',
    title: 'Spirulina Powder',
    description: 'Perfect for cold Canadian winters',
    price: 45.18,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=17',
    category: 'grocery',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '18',
    title: 'Vitamin C Tablets',
    description: 'Vegan, cruelty-free and eco-friendly',
    price: 68.45,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=18',
    category: 'beauty',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '19',
    title: 'Kombucha Starter Kit',
    description: 'Made with natural Canadian ingredients',
    price: 60.86,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=19',
    category: 'health',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '20',
    title: 'Ice Skates',
    description: 'Crafted in small batches in Ontario',
    price: 39.41,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=20',
    category: 'pharmacy',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '21',
    title: 'Hand Cream',
    description: 'Harvested fresh from Nova Scotia',
    price: 83.25,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=21',
    category: 'health',
    isMadeInCanada: true,
    amazonUrl: '',
    walmartUrl: '',
  },
  {
    id: '22',
    title: 'Beard Oil',
    description: 'Perfect for cold Canadian winters',
    price: 17.24,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=22',
    category: 'grocery',
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '23',
    title: 'Sleep Gummies',
    description: 'Infused with maple and lavender',
    price: 87.91,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=23',
    category: 'health',
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '24',
    title: 'Antibacterial Spray',
    description: 'Sourced sustainably from BC forests',
    price: 31.95,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=24',
    category: 'beauty',
    isMadeInCanada: true,
    amazonUrl: '',
    walmartUrl: '',
  },
  {
    id: '25',
    title: 'Rose Water Spray',
    description: 'Crafted in small batches in Ontario',
    price: 12.33,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=25',
    category: 'beauty',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '26',
    title: 'Arnica Gel',
    description: 'Perfect for cold Canadian winters',
    price: 28.03,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=26',
    category: 'health',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '27',
    title: 'Arnica Gel',
    description: 'Popular among Canadian athletes',
    price: 99.22,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=27',
    category: 'grocery',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '28',
    title: 'Kombucha Starter Kit',
    description: 'Crafted in small batches in Ontario',
    price: 32.63,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=28',
    category: 'beauty',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '29',
    title: 'Natural Deodorant',
    description: 'Vegan, cruelty-free and eco-friendly',
    price: 87.91,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=29',
    category: 'grocery',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '30',
    title: 'Muscle Rub',
    description: 'Sourced sustainably from BC forests',
    price: 43.96,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=30',
    category: 'pharmacy',
    isMadeInCanada: true,
    amazonUrl: '',
    walmartUrl: '',
  },
  {
    id: '31',
    title: 'Ginger Chews',
    description: 'Harvested fresh from Nova Scotia',
    price: 21.73,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=31',
    category: 'grocery',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '32',
    title: 'Elderberry Syrup',
    description: 'Family-owned brand from Alberta',
    price: 29.32,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=32',
    category: 'pharmacy',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '33',
    title: 'Recycled Notebook',
    description: 'Infused with maple and lavender',
    price: 80.2,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=33',
    category: 'pharmacy',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '34',
    title: 'Peppermint Lip Balm',
    description: 'Crafted in small batches in Ontario',
    price: 95.12,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=34',
    category: 'grocery',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '35',
    title: 'Thermal Socks',
    description: 'Crafted in small batches in Ontario',
    price: 5.74,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=35',
    category: 'pharmacy',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '36',
    title: 'Apple Chips',
    description: 'Vegan, cruelty-free and eco-friendly',
    price: 56.91,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=36',
    category: 'health',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '37',
    title: 'Hemp Protein Powder',
    description: 'Popular among Canadian athletes',
    price: 51.55,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=37',
    category: 'pharmacy',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '38',
    title: 'Ice Skates',
    description: 'Made with natural Canadian ingredients',
    price: 21.64,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=38',
    category: 'health',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '39',
    title: 'Granola Mix',
    description: 'Perfect for cold Canadian winters',
    price: 76.84,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=39',
    category: 'grocery',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '40',
    title: 'Kombucha Starter Kit',
    description: 'Harvested fresh from Nova Scotia',
    price: 18.91,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=40',
    category: 'grocery',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '41',
    title: 'Granola Mix',
    description: 'Top seller in Canadian organic markets',
    price: 32.43,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=41',
    category: 'beauty',
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '42',
    title: 'Black Currant Lozenges',
    description: 'Vegan, cruelty-free and eco-friendly',
    price: 85.1,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=42',
    category: 'pharmacy',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '43',
    title: 'Body Wash',
    description: 'Sourced sustainably from BC forests',
    price: 84.45,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=43',
    category: 'grocery',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '44',
    title: 'Magnesium Oil',
    description: 'Harvested fresh from Nova Scotia',
    price: 66.68,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=44',
    category: 'health',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '45',
    title: 'Apple Chips',
    description: 'Top seller in Canadian organic markets',
    price: 67.48,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=45',
    category: 'beauty',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '46',
    title: 'Charcoal Toothpaste',
    description: 'Infused with maple and lavender',
    price: 83.96,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=46',
    category: 'grocery',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '47',
    title: 'Antibacterial Spray',
    description: 'Made with natural Canadian ingredients',
    price: 57.41,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=47',
    category: 'pharmacy',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '48',
    title: 'Energy Bar',
    description: 'Made with natural Canadian ingredients',
    price: 9.71,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=48',
    category: 'beauty',
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: '',
  },
  {
    id: '49',
    title: 'Bamboo Toothbrush',
    description: 'Sourced sustainably from BC forests',
    price: 63.4,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=49',
    category: 'beauty',
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '50',
    title: 'Hand Cream',
    description: 'Top seller in Canadian organic markets',
    price: 75.9,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=50',
    category: 'beauty',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '51',
    title: 'Recycled Notebook',
    description: 'Crafted in small batches in Ontario',
    price: 88.26,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=51',
    category: 'health',
    isMadeInCanada: true,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '52',
    title: 'Hand Cream',
    description: 'Harvested fresh from Nova Scotia',
    price: 78.45,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=52',
    category: 'beauty',
    isMadeInCanada: true,
    amazonUrl: '',
    walmartUrl: '',
  },
  {
    id: '53',
    title: 'Gluten-Free Flour',
    description: 'Infused with maple and lavender',
    price: 21.07,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=53',
    category: 'pharmacy',
    isMadeInCanada: true,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '54',
    title: 'Vitamin C Tablets',
    description: 'Infused with maple and lavender',
    price: 92.89,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=54',
    category: 'health',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '55',
    title: 'Body Wash',
    description: 'Top seller in Canadian organic markets',
    price: 16.2,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=55',
    category: 'beauty',
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: '',
  },
  {
    id: '56',
    title: 'Hand Cream',
    description: 'Sourced sustainably from BC forests',
    price: 26.94,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=56',
    category: 'pharmacy',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '57',
    title: 'Zinc Supplements',
    description: 'Family-owned brand from Alberta',
    price: 76.02,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=57',
    category: 'beauty',
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: '',
  },
  {
    id: '58',
    title: 'Ice Skates',
    description: 'Sourced sustainably from BC forests',
    price: 84.97,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=58',
    category: 'pharmacy',
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '59',
    title: 'Natural Mascara',
    description: 'Family-owned brand from Alberta',
    price: 85.16,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=59',
    category: 'pharmacy',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '60',
    title: 'Beard Oil',
    description: 'Harvested fresh from Nova Scotia',
    price: 78.94,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=60',
    category: 'health',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '61',
    title: 'Gluten-Free Flour',
    description: 'Made with natural Canadian ingredients',
    price: 37.19,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=61',
    category: 'health',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '62',
    title: 'Bamboo Toothbrush',
    description: 'Sourced sustainably from BC forests',
    price: 72.42,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=62',
    category: 'beauty',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '63',
    title: 'Probiotic Capsules',
    description: 'Vegan, cruelty-free and eco-friendly',
    price: 38.84,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=63',
    category: 'beauty',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '64',
    title: 'Zinc Supplements',
    description: 'Infused with maple and lavender',
    price: 8.23,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=64',
    category: 'beauty',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '65',
    title: 'Rose Water Spray',
    description: 'Popular among Canadian athletes',
    price: 81.71,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=65',
    category: 'pharmacy',
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '66',
    title: 'Hand Cream',
    description: 'Family-owned brand from Alberta',
    price: 26.22,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=66',
    category: 'beauty',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '67',
    title: 'Ginger Chews',
    description: 'Family-owned brand from Alberta',
    price: 74.15,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=67',
    category: 'health',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '68',
    title: 'Body Wash',
    description: 'Made with natural Canadian ingredients',
    price: 6.83,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=68',
    category: 'pharmacy',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '69',
    title: 'Trail Mix',
    description: 'Harvested fresh from Nova Scotia',
    price: 66.01,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=69',
    category: 'pharmacy',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '70',
    title: 'Vitamin C Tablets',
    description: 'Harvested fresh from Nova Scotia',
    price: 85.95,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=70',
    category: 'health',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '71',
    title: 'Body Wash',
    description: 'Perfect for cold Canadian winters',
    price: 45.74,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=71',
    category: 'pharmacy',
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '72',
    title: 'Hand Cream',
    description: 'Family-owned brand from Alberta',
    price: 26.73,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=72',
    category: 'health',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '73',
    title: 'Peppermint Lip Balm',
    description: 'Family-owned brand from Alberta',
    price: 50.09,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=73',
    category: 'beauty',
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: '',
  },
  {
    id: '74',
    title: 'Zinc Supplements',
    description: 'Made with natural Canadian ingredients',
    price: 88.97,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=74',
    category: 'beauty',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '75',
    title: 'Energy Bar',
    description: 'Crafted in small batches in Ontario',
    price: 53.54,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=75',
    category: 'pharmacy',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '76',
    title: 'Rose Water Spray',
    description: 'Made with natural Canadian ingredients',
    price: 84.78,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=76',
    category: 'pharmacy',
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '77',
    title: 'Ginger Chews',
    description: 'Harvested fresh from Nova Scotia',
    price: 68.32,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=77',
    category: 'health',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '78',
    title: 'Ice Skates',
    description: 'Made with natural Canadian ingredients',
    price: 34.02,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=78',
    category: 'grocery',
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: '',
  },
  {
    id: '79',
    title: 'Face Toner',
    description: 'Crafted in small batches in Ontario',
    price: 29.74,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=79',
    category: 'beauty',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '80',
    title: 'Peppermint Lip Balm',
    description: 'Top seller in Canadian organic markets',
    price: 67.56,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=80',
    category: 'grocery',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '81',
    title: 'Beard Oil',
    description: 'Popular among Canadian athletes',
    price: 18.34,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=81',
    category: 'health',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '82',
    title: 'Sleep Gummies',
    description: 'Sourced sustainably from BC forests',
    price: 33.15,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=82',
    category: 'health',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '83',
    title: 'Arnica Gel',
    description: 'Popular among Canadian athletes',
    price: 5.86,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=83',
    category: 'beauty',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '84',
    title: 'Salmon Jerky',
    description: 'Family-owned brand from Alberta',
    price: 36.26,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=84',
    category: 'health',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '85',
    title: 'Eucalyptus Oil',
    description: 'Infused with maple and lavender',
    price: 55.13,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=85',
    category: 'pharmacy',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '86',
    title: 'Salmon Jerky',
    description: 'Perfect for cold Canadian winters',
    price: 29.11,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=86',
    category: 'pharmacy',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '87',
    title: 'Aloe Vera Gel',
    description: 'Crafted in small batches in Ontario',
    price: 72.73,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=87',
    category: 'health',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '88',
    title: 'Energy Bar',
    description: 'Perfect for cold Canadian winters',
    price: 18.38,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=88',
    category: 'beauty',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '89',
    title: 'Spirulina Powder',
    description: 'Popular among Canadian athletes',
    price: 95.07,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=89',
    category: 'health',
    isMadeInCanada: true,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '90',
    title: 'Peppermint Lip Balm',
    description: 'Perfect for cold Canadian winters',
    price: 93.33,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=90',
    category: 'grocery',
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '91',
    title: 'Arnica Gel',
    description: 'Perfect for cold Canadian winters',
    price: 28.45,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=91',
    category: 'health',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '92',
    title: 'Gluten-Free Flour',
    description: 'Harvested fresh from Nova Scotia',
    price: 51.77,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=92',
    category: 'pharmacy',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '93',
    title: 'Ginger Chews',
    description: 'Infused with maple and lavender',
    price: 19.89,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=93',
    category: 'health',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '94',
    title: 'Maple Soap',
    description: 'Harvested fresh from Nova Scotia',
    price: 71.95,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=94',
    category: 'health',
    isMadeInCanada: true,
    amazonUrl: '',
    walmartUrl: '',
  },
  {
    id: '95',
    title: 'Organic Shampoo',
    description: 'Infused with maple and lavender',
    price: 69.76,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=95',
    category: 'health',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '96',
    title: 'Magnesium Oil',
    description: 'Infused with maple and lavender',
    price: 7.65,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=96',
    category: 'grocery',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '97',
    title: 'Pumpkin Seed Butter',
    description: 'Infused with maple and lavender',
    price: 98.65,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=97',
    category: 'beauty',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '98',
    title: 'Energy Bar',
    description: 'Harvested fresh from Nova Scotia',
    price: 30.79,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=98',
    category: 'grocery',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '99',
    title: 'Trail Mix',
    description: 'Perfect for cold Canadian winters',
    price: 53.18,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=99',
    category: 'pharmacy',
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '100',
    title: 'Natural Mascara',
    description: 'Family-owned brand from Alberta',
    price: 16.05,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=100',
    category: 'grocery',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '101',
    title: 'Eye Cream',
    description: 'Sourced sustainably from BC forests',
    price: 53.25,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=101',
    category: 'pharmacy',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '102',
    title: 'Natural Deodorant',
    description: 'Harvested fresh from Nova Scotia',
    price: 72.88,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=102',
    category: 'health',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '103',
    title: 'Spirulina Powder',
    description: 'Family-owned brand from Alberta',
    price: 96.9,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=103',
    category: 'beauty',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '104',
    title: 'Arnica Gel',
    description: 'Perfect for cold Canadian winters',
    price: 95.55,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=104',
    category: 'pharmacy',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '105',
    title: 'Lemon Balm Tea',
    description: 'Sourced sustainably from BC forests',
    price: 96.43,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=105',
    category: 'pharmacy',
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '106',
    title: 'Chia Seeds',
    description: 'Sourced sustainably from BC forests',
    price: 41.66,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=106',
    category: 'pharmacy',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '107',
    title: 'Zinc Supplements',
    description: 'Harvested fresh from Nova Scotia',
    price: 30.74,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=107',
    category: 'beauty',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '108',
    title: 'Trail Mix',
    description: 'Popular among Canadian athletes',
    price: 49.89,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=108',
    category: 'pharmacy',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '109',
    title: 'Reusable Cotton Pads',
    description: 'Family-owned brand from Alberta',
    price: 91.27,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=109',
    category: 'grocery',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '110',
    title: 'Organic Tea',
    description: 'Vegan, cruelty-free and eco-friendly',
    price: 75.16,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=110',
    category: 'health',
    isMadeInCanada: false,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: '',
  },
  {
    id: '111',
    title: 'Sleep Gummies',
    description: 'Sourced sustainably from BC forests',
    price: 87.96,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=111',
    category: 'health',
    isMadeInCanada: false,
    amazonUrl: '',
    walmartUrl: 'https://walmart.ca',
  },
  {
    id: '112',
    title: 'Hair Conditioner',
    description: 'Top seller in Canadian organic markets',
    price: 16.49,
    imageSrc: 'https://source.unsplash.com/random/300x300?sig=112',
    category: 'grocery',
    isMadeInCanada: true,
    amazonUrl: 'https://amazon.ca',
    walmartUrl: 'https://walmart.ca',
  },
];

export const categories: Category[] = [
  { id: 'all', name: 'All Products' },
  { id: 'grocery', name: 'Grocery' },
  { id: 'health', name: 'Health' },
  { id: 'beauty', name: 'Beauty' },
  { id: 'pharmacy', name: 'Pharmacy' },
];
